### ISSUE TITLE
Free pythonista training

### ISSUE THREAD

**Issue by Metallicow** [Correct-Syntax/Gimel-Studio#10]
@Correct-Syntax 
Some words of wisdom here. I've looked over some of your source files and really you need a bit of pythonista training. It really shows.

ZeroRule:
Trim all trailing whitespace in both files before diffing or commiting.  This rule is next to godliness... or next to headaches.
Back in the day, before when Al Gore invented the internet, we used to send *.txt files back and forth across a froz-ma-kom-baa-baz-ulator which most noobs today call email. Then you had to trim the files yourself, and then review them. Most often, you would get a half-happy/half-nasty reply back with your files(all whitespace trimmed lol). And then they would proceed to 'lash' thy back with a whip for every whitespace character found.  Plz trim thy evil whitespace demons!

First watch this!
[Transforming Code into Beautiful, Idiomatic Python](https://www.youtube.com/watch?v=OSGv2VnC0go)

Review how many of these you are guilty of...
[Python Speed Tips](https://wiki.python.org/moin/PythonSpeed/PerformanceTips)

Lastly, apply style changes to make ugly lines that formatters make into 3+ lines into 1 or less.

We would hope the BLA  variable here makes some sort of sense.
### BLA = variable

Please if you have to... Only use your formatter once, NOT ALWAYS!.  The first and only time you ever use one of these horrible/glorious *things* upon your code. Ex: PEP8/PyCodeStyle/Black/HomemadeWhatever
2nd. Fix what it "corrected" that it did wrong.
Learn. Do it the manual way. Profit!

... You will eventually get faster and more efficient doing things spotting them manually without thinking about using a "code wrecker" upon it, which 90% of the time makes your code "worse".

# Ugly
```python
        self._mgr.GetArtProvider().SetMetric(
            aui.AUI_DOCKART_SASH_SIZE,
            2
            )
```
# Faster and BLA
```python
        _mgr = self._mgr
        art = _mgr.GetArtProvider()
        art.SetMetric(aui.AUI_DOCKART_SASH_SIZE, 2)  # Less than 79 characters...
        ... etc, etc, etc....
```

Ex: some more of the ugliness...
# Ugly
```python
        elif event.LeftIsDown() == True \
            and self._srcNode == None and self._bboxStart != None:
```
# Faster and BLA
```python
        elif (event.LeftIsDown() and 
              self._srcNode is None and 
              self._bboxStart is not None):
```

... If your excited, plenty more follow!

... Hope this is a starter ....

**Comment by Correct-Syntax** [comment]
> Some words of wisdom here. I've looked over some of your source files and really you need a bit of pythonista training. It really shows.

Thank you. I spend a lot more time *coding* than *learning how to* code -when it's really necessary to do both and I should do both. ;)

> ZeroRule....

This is not really something I think about, honestly -But I do get the point of eliminating those spaces.

> Please if you have to... Only use your formatter once, NOT ALWAYS!.... 

I don't actually use a code formatter. So, I guess the ugliness would be my own fault. I try to follow Pep8 standards....when I remember. Honestly though, you came in at the "worst time" because I just finished moving code around here-and-there and added/subtracted stuff (somewhat of a half-rewrite of the core code). I hadn't gotten around to doing some "housekeeping" with the code yet. Though, I will admit it still probably wouldn't be to standards.

Thanks for the advice. 👍
