### ISSUE TITLE
Need scroll bar inside of node properties

### ISSUE THREAD

**Issue by iwoithe** [Correct-Syntax/Gimel-Studio#15]
I've started writing a text node, however I have come across a problem.

![screenshot](https://user-images.githubusercontent.com/73422868/97144176-e5fbc780-17b3-11eb-9fc2-c6918a64c698.png)

I have run out of space for the parameters of this node, and there are still quite a few parameters I need to add. Adding a scroll bar to the node properties would solve this.

**Comment by Correct-Syntax** [comment]
@iwoithe, thank you for your work on this.

This is a known issue. When I was creating the "add text" node myself (see the v0.4.2  source code to see my beginning code -with the old api, though) I ran into this problem. Though, I never implemented the scrollbar because I had a different "road block" that needed to be fixed first. Namely, the renderer threading. (Still to be resolved). You may run into this too, eventually. 

Anyway, this looks good and I will try to find some time to implement this Really soon.

Note: I am sure you've probably picked this up, but in order to create new properties, subclass the ```Property``` class from the api.

Thanks again. 👍

**Comment by Correct-Syntax** [comment]
I've implemented this. It's in the master branch now.

**Comment by iwoithe** [comment]
Hi @Correct-Syntax,
While testing the text node on Windows (primarily for #18), I discovered that I couldn't see the font color property.
![property_panel_issue](https://user-images.githubusercontent.com/73422868/97770788-6b052900-1b86-11eb-8ed9-2dc66ebda6b4.png)
I don't know why I couldn't scroll any further, but when I resized the node properties panel (bigger), I could see it.

**Comment by Correct-Syntax** [comment]
Hmmm. I will take a look at this.

My first thought is that it could be that when you're scrolling the mouse wheel, the event is going to one of the properties (because your mouse cursor is over them) instead of to the panel itself. Not sure if this is the issue you are having, but it's happened to me a few times during testing.

In any case, I will take a peek at it....

**Comment by Metallicow** [comment]
@iwoithe Please post what Python/wxPython versions you are using.
@Correct-Syntax You should setup a issue-template for github with these two lines so folks making issues will fill in relevant infos if they may be necessary.

By doing this it makes it easier for me/others to quickly see if it is a problem with your version rather than maybe a mishap in the gimel codebase. wxPy 4.1 fixes a lot of event stuff for example and will cause issues with certain widgets atm.

**Comment by iwoithe** [comment]
> @iwoithe Please post what Python/wxPython/OS versions you are using.

OS: Windows 10
Python: 3.7.8
wxPython: 4.1.0

**Comment by Metallicow** [comment]
Everything seems to work fine on Py3.8/Win7 as far as the scrolled window is concerned.
It looks like the wx.App MouseWheel function needs to be tweaked so you know what is being hovered. I have an example of this at the application level in my sample-apps-and-demos repo for new wxPy demo framework. It handles most classes in a single method.
It's either that or edit all the plugins to accommodate for mouse_events. Hooking in the wx.App way is easier since editing #### of plugins would be a headache and more maint.

**Comment by Correct-Syntax** [comment]
@Metallicow 

> You should setup a issue-template for github with these two lines so folks making issues will fill in relevant infos if they may be necessary.

Good idea. I've done this. Though maybe I should add the Python version as well....

**Comment by Metallicow** [comment]
@Correct-Syntax Yep, these are your basic infos. Basically the same as wxPython form since it is your gui kit. Easiest way to force a user to do some sort of work so you don't have to waste time spamming everyone as to please post this or that questions.
At a certain point you will be able to answer some questions just by looking at this stuff without even running code, because you might have been a duplicate issue. Ex: dds wasn't supported on some older pil versions and issuer was to lazy to rtfm.


**System (please complete the following information):**
 - OS: [e.g. Windows, Linux Mint] Win7x64
 - Python Version [e.g. 2.7.18, 3.8.6] Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:19:08) [MSC v.1500 32 bit (Intel)] on win32
 - wxPython Version [e.g. 4.0.7.post2, 4.1.1] wxPython 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5 Scintilla 3.21
- Other Imaging Libs if suspect [e.g Pillow 8.0, ImageMagick x.x.x, etc...]

**Comment by Correct-Syntax** [comment]
O.k. This seems to be fixed. Feel free to let me know if its not. :)
