### ISSUE TITLE
Error when startin v0.4.2 on linux

### ISSUE THREAD

**Issue by MarioPeper** [Correct-Syntax/Gimel-Studio#3]
Hello Noah, now the submission seems to work :-)
But I can't start Gimel-Studio v0.4.2 because I found 2 problems. The first one is simple: On Linux you should not have spaces in the folder name or in the executable. I renamed it to Gimel_Studio. gimelstudio would probably be better. But I have attached another error message.
[gimel01.txt](https://github.com/Correct-Syntax/Gimel-Studio/files/5181401/gimel01.txt)

Thanks Mario

**Comment by Correct-Syntax** [comment]
Hi Mario,

First problem: Yes, you are right. It shouldn't have spaces. I usually do the command with quotes, but you're right about it as that is unnecessary. I will fix that in the next release. 👍 
Second problem: Thank you for the error message. I will look into this. Your on Ubuntu, right? Could you share your system version?

Thanks again.

**Comment by MarioPeper** [comment]
Ich bin auf 18.04.5 LTS

**Comment by Correct-Syntax** [comment]
O.k. Thank you. 👍 

I have looked into this and I believe it is because you need at least Ubuntu 20.04.1 LTS.

I have built the Gimel Studio executable on Linux Mint 20

The error seems to say that the required versions of libraries needed to run the application are not available on 18.04.5 LTS. [link to stackoverflow question](https://stackoverflow.com/questions/59145051/glibc-2-27-not-found-ubuntu-16-04)

I would try upgrading your system to Ubuntu 20.04.1 LTS. Then, I am confident it will run correctly. If you would rather not upgrade, then you could build Gimel Studio from source too.

Thanks.

**Comment by Correct-Syntax** [comment]
I am also going to include this information on the website download section and docs since it seems the built executable will work only on Ubuntu 20.04.1 LTS+.

**Comment by Correct-Syntax** [comment]
@MarioPeper sorry about this. Just let me know if you would like to build from source. I would be happy to assist you.

**Comment by MarioPeper** [comment]
Thank you for looking at it. I will just compile it myself the next days.

**Comment by Correct-Syntax** [comment]
O.k. Let me know if you need any help. :)

I appreciate your feedback.

**Comment by MarioPeper** [comment]
Unfortunately I can't get v0.4.2 to work.
bash: ./make: No permission
and when I change the "execute file as program
comes:
./make: Line 1: pyinstaller: command not found

Keep in mind that this is translated as Deepl. So the command output could be slightly different.

But why does v0.3 work ...is there such a big difference?

**Comment by Correct-Syntax** [comment]
O.k. Thank you for trying this. 👍 
Here are some steps you can do: (please note I am doing this quickly...)
1. get the source, `git clone`.... (I am sure you know how to do that)
2. `python3 --version` -if this doesn't show you the version of python you don't have it and need to get Python 3.
3. `pip --version` -if this doesn't show you the version of pip you need to get it.

Please confirm you have those as a start. Then we can continue....

**Comment by Correct-Syntax** [comment]
4. `pip3 install pipenv` -this installs pipenv
5. `pipenv shell` -this launches the virtual env

Now you are set up to install the dependencies, which is as simple as running (still in the shell from step 5):
`pipenv install`
This may take a bit to install the dependencies.

**Comment by Correct-Syntax** [comment]
(You will now be at the step 2. in the README instructions.):

You should be able to now run `python3 "src/Gimel Studio.py"` to launch Gimel Studio.

If you would like to build the executable, the make file is suppposed to do that. However, just like you had mentioned, it doesn't work. Just copy and paste the command(s) from the make file into the console and run them.

**Comment by Correct-Syntax** [comment]
You should find the executable in the `dist` folder.

I really hope this make sense and ends in you having the built executable. If not, please let me know and I will help as much as I can. :)

**Comment by Correct-Syntax** [comment]
The reason v0.3.0 works (most likely) is the same reason the v0.4.0 and v0.4.2 executables didn't work for you. :) I switched/upgraded my system from Linux Mint 19 to Linux Mint 20 LTS right after I released v0.3.0. So, from v0.4.0 and onward I have built the executables on 20 LTS instead of the 19 I was using with v0.3.0.

Thank you for your patience. Please do let me know if you have any other issues. :)

**Comment by MarioPeper** [comment]
O.K. a bit closer now :-)
~/programme/Gimel_dev/Gimel-Studio$ python3 "src/Gimel Studio.py"
Traceback (most recent call last):
  File "src/Gimel Studio.py", line 22, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

and with make (copied)

$ pyinstaller -n "GimelStudio" --hidden-import pkg_resources.py2_warn "src/Gimel Studio.py"
pyinstaller: Befehl nicht gefunden.

"Befehl nicht gefunden" means: command not found

but i have 

$ python3 --version
Python 3.6.9

$ pip3 --version
pip 20.2.3 from /home/user/.local/lib/python3.6/site-packages/pip (python 3.6)

**Comment by Correct-Syntax** [comment]
This sounds like you haven't installed the dependencies.

What happens when you type `pipenv` in your shell?

**Comment by Correct-Syntax** [comment]
If there is an error, you need to install it with `pip3 install pipenv`. :)

**Comment by Correct-Syntax** [comment]
I'm sorry if I am confusing you with all of this. I am not sure if you have development experience or not -but the easiest way for you to get up and going would be to just do the following (instead of worrying about setting up a virtual environment first and having the problems/headaches that often come from it):

1. Run each of these commands (these install the dependencies):
`pip3 install opencv-python`
`pip3 install numpy`
`pip3 install scipy`
`pip3 install pillow`

2. Download this [wheel file for wxpython](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.0-cp36-cp36m-linux_x86_64.whl)

3. Install the file you downloaded with `pip3 install <pathtothatfilehere>`

4. Run Gimel Studio with `python3 "src/Gimel Studio.py"`!

This won't build the executable, but this will get you very close and you will be able to try the program right away.

Please let me know how this works. Thank you. 👍

**Comment by MarioPeper** [comment]
Yes, it's running now. I couldn't have done it without your help.
It's not like I haven't compiled anything myself yet. But these are only things like Mandelbulber for example, which works without problems. But I prefer binary ones. :-)
Now I will experiment a little bit with it and then I have some suggestions. Should I post them all here or rather via email.
Thanks again for your help

**Comment by Correct-Syntax** [comment]
That's great! HalleluYAH! Glad it worked for you. 👍 

It would be great if you could open a Github pull request for your suggestions as it is easier to handle than via email.

Note: to build the executable:
`pip3 install pyinstaller`
Then copy the contents of the `make` file into you console (or run the `./make` if you can) and run it. The executable will be in the `dist` folder.
