### ISSUE TITLE
Keyboard shortcuts do not work

### ISSUE THREAD

**Issue by MarioPeper** [Correct-Syntax/Gimel-Studio#4]
When I start Gimel-Studio from Python, after some time no more shortcuts work (Note: this was also the case with blender 2.82 linux.) . Fullscreen does not work either. When I start Gimel-Studio as compiled binary no shortcuts work from the beginning. Here also my suggestion would be to really use the Blender shortcuts and not just roughly. Instead of "alt+x" "x" or "Ctrl+x" etc. Del should also work. And then of course "Shift+A" would make sense for the menu in addition to right click, because of muscle memory.

**Comment by Correct-Syntax** [comment]
This is actually a known issue. On Windows they work fine, but on the Linux version the shortcuts don't seem to always work. I am not sure what is up with this. Since you mentioned blender having the same problem, it may be an issue with Ubuntu?? I will look into this though.

 Thanks for reporting it!

**Comment by Correct-Syntax** [comment]
Blender shortcuts: Well, this is a good suggestion for blender users, but I am not sure if this is a good idea for people that haven't used Blender before.

My goal is to use the "conventional" keyboard shortcuts for things. (e.g: Ctrl+S for save) 

Would you be willing to do a little research for me to see if all of the shortcuts blender uses are "conventional"?

 I know that prior to the 2.8 release, they were not. Now, I believe they are more along the lines of conventional, but I am not 100% on that.

**Comment by MarioPeper** [comment]
I think it is perfectly ok to use standard layouts. I just thought it should be blender like because I don't know any other program that uses alt+x or Ctrl+x or even x to delete. Then with the look of the editor ;-)
Yes there is a so called industry standard shortcuts in the preferences for new and switching ones. But I did not look at it. But of course Ctrl+s, Ctrl+c Ctrl+v etc. works in blender too.

**Comment by Correct-Syntax** [comment]
Yeah. 👍

**Comment by Correct-Syntax** [comment]
> When I start Gimel-Studio from Python, after some time no more shortcuts work (Note: this was also the case with blender 2.82 linux.) . 

The same thing happens for me on linux mint. This is definitely an issue with linux/wxpython on linux/my code on linux -since windows does not seem to have this issue.

@Metallicow, do you know anything about what may be causing this?

**Comment by Metallicow** [comment]
@Correct-Syntax Plz add stuff to your .github-issue-template if clogging the issue dept with blender related stuff...(I'd tend to like to be pinged if I haven't replied to a subject)
When it comes to keyboard shortcuts, it it a hard issue.
When you start a wxPy program you have initial startup. This is normal.
I can of course STOMP on whatever shortcut I want, by doing so in code.
mdk/Wings3D/Blender/SDS2 may do the same thing while running so you the `user` has to really make the decision on who is the boss.

x Prog Ctrl+x
might stomp on
y prog Ctrl+x
while I could stomp and be frog king by.
Ctrl+x will always ReleaseHotAirBalloon42()
hard to say... lol

**Comment by Metallicow** [comment]
The best thing to do is NOT to argue about keyboard shortcuts. Even the most advanced programs and my own do not care really since it is a .settingsfile or somesuch.
This is usually dealt with on the users end and if anything is STOMPING, then deal with it however you can by making a STOMP OPTION. Tho almost 99.9 percent of users using your program will not like a STOMP option by default(just like FULLSCREEN ON STARTUP).
Provide a checkbox option [x] Plz dont FROGSTOMP my settings next startup....

**Comment by Metallicow** [comment]
If you create a wx.MenuBar with wx.Menu's and define all IDs then you **should** be able to call any IDs from anywhere as long as your program has focus and no stomping.
You can also take handle of App things by sticking event handlers here and there if you get fancy.
Of course, The most EVIL program would be to try and to take complete control of everything. 
I can see, you are still learning...

**Comment by Correct-Syntax** [comment]
> Plz add stuff to your .github-issue-template if clogging the issue dept with blender related stuff...(I'd tend to like not to be pinged if I haven't replied to a subject)

Yes, I need to update the issue template with more information. This was opened before I had the issue template. Sorry.

Also, *sorry* if you didn't want to be involved in this issue. I just thought that since you seem to be "in the know" with wxpython (both in contrib and experience), maybe you might have an idea if this was an issue with wxpython or whatever.

> I can of course STOMP on whatever shortcut I want, by doing so in code.
mdk/Wings3D/Blender/SDS2 may do the same thing while running so you the user has to really make the decision on who is the boss.

x Prog Ctrl+x
might stomp on
y prog Ctrl+x
while I could stomp and be frog king by.
Ctrl+x will always ReleaseHotAirBalloon42()
hard to say... lol

I can't say I really understood all that, but I have to think it's related to

> When it comes to keyboard shortcuts, it it a hard issue.

**Comment by Correct-Syntax** [comment]
> The best thing to do is NOT to argue about keyboard shortcuts. Even the most advanced programs and my own do not care really since it is a .settingsfile or somesuch.

Agreed.

> This is usually dealt with on the users end and if anything is STOMPING, then deal with it however you can by making a STOMP OPTION. Tho almost 99.9 percent of users using your program will not like a STOMP option by default(just like FULLSCREEN ON STARTUP).
Provide a checkbox option [x] Plz dont FROGSTOMP my settings next startup....

Can you explain this for me? I speak English and a bit of Spanish...but I don't understand what STOMP, FROGSTOMP, etc is (unless you mean keyboard smashing?) though. :)

**Comment by Correct-Syntax** [comment]
> If you create a wx.MenuBar with wx.Menu's and define all IDs then you should be able to call any IDs from anywhere as long as your program has focus and no stomping.

O.k. I will try that. Thanks.

> I can see, you are still learning...

Of course. That's the reason I have "always learning new things" above my Github profile (hover over my user avatar to the left to see it). I certainly have yet to master WxPython and other things (would you believe this is actually my first "real" project using wxpython -yes, it probably shows, but that why you're here).

**Comment by Metallicow** [comment]
No, I wasn't trying to be funny per say, but python is idiomatic at times, so basically just anaysing the shortcuts for the 2 or more programs and create a settings file that bridges them is usually enough.
Some times you might run into what is called duck typing. This has a bit of different meaning if you are using this in a musical context.
Ex: in music there are no keys, just sound and flow. Think of this similar to pi. 3.14159
Ex: ctrl-x and ctrl-x might be mapped to cut and cat. tau, ta, tah, tao, or taw, have multiple spellings ...
Sorry if that sounds a little bit weird. Some might spell it eddie-o-matic if they are trying to be funny in the music room.
But the end point is that you or the reader should be able to sound out what is written, to try and avoid problematic translations of defs, or in word fragments of speech. Hope this helps.

**Comment by Metallicow** [comment]
Normally a STOMP is where one program will override both programs or reroute your mapping to try an avoid conflicts. Most often times in python there will be some sort of animal joke, so in this case if you are using yourself as a stomping point take RAHMSTOMP or RAMSTOMP into consideration, but not in the context that you are stomping of the computer ram.
Think of the first stomp file will be linked to what you want to happen in gimel and the second file would be mapped to blender for example.

**Comment by Metallicow** [comment]
You will probably want to look into the wxPython docs. There is a function to register a systemwide hotkey.
see https://wiki.wxpython.org/RegisterHotKey

**Comment by Correct-Syntax** [comment]
Thank you @Metallicow for the suggestion. 

I've been trying to find a way to bind the keys systemwide, but for Linux. On Windows it seems to work with the current implementation, but not on Linux Ubuntu -so I am not sure if the recipe will work since it says it "Works only under MS Windows".

Have any ideas for Linux? I am not sure if it is the *way* that I am binding them that causes issues for Linux or what the problem is, tbh.
